version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - setup

  setup:
    build: .
    volumes:
      - .:/var/www/html
    command: >
      sh -c "
        php artisan migrate --force &&
        php artisan whatsapp:sync-status
      "
    restart: "no"

  scheduler:
    build: .
    volumes:
      - .:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      sh -c "
        while true; do
          php artisan whatsapp:sync-status
          sleep 60
        done
      "
    depends_on:
      - setup