<?php

namespace App\Filament\Resources\WhatsAppInstanceResource\Pages;

use App\Filament\Resources\WhatsAppInstanceResource;
use App\Services\DockerService;
use Filament\Resources\Pages\CreateRecord;

class CreateWhatsAppInstance extends CreateRecord
{
    protected static string $resource = WhatsAppInstanceResource::class;

    protected function afterCreate(): void
    {
        $dockerService = app(DockerService::class);

        try {
            $dockerService->createContainer($this->record);
        } catch (\Exception $e) {
            $this->record->update(['status' => 'error']);
            throw $e;
        }
    }

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['port'] = random_int(4000, 5000); // Random port for the instance

        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
